import grpc
from concurrent import futures
import booking_pb2
import booking_pb2_grpc
import uuid
from datetime import datetime
from typing import Any, List, Dict
from kafka_consumer import KafkaConsumerService
import logging
import psycopg2

logging.basicConfig(
    level=logging.INFO, # Set the minimum level to log (DEBUG, INFO, WARNING, ERROR, CRITICAL)
    format='%(asctime)s - %(levelname)s - %(message)s', # Define the output format
    datefmt='%Y-%m-%d %H:%M:%S' # Define the timestamp format
)

def crate_table_if_missing():

    conn = psycopg2.connect(
                 dbname="booking-history",
                 user="booking-history",
                 password="booking-history",
                 host="booking-history-db",
                 port="5432"
                )    
    cur = conn.cursor()
    # SQL for table creation
    create_table_query = """
    CREATE TABLE IF NOT EXISTS "booking-history" (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_id TEXT NOT NULL,
        hotel_id TEXT NOT NULL,
        price DOUBLE PRECISION NOT NULL,
        created_at TIMESTAMPTZ NOT NULL
    );
    """

    try:
        cur.execute(create_table_query)
        conn.commit()
        logging.info("Table 'booking-history' created successfully.")
    except Exception as e:
        logging.info(f"Error creating table: {e}")
        conn.rollback()
    finally:
        cur.close()
        conn.close()

def handler(booking:Dict[str, Any]):
               
        logging.info("Handling booking creation...")
        new_id = -1
        try :
            conn = psycopg2.connect(
                    dbname="booking-history",
                    user="booking-history",
                    password="booking-history",
                    host="booking-history-db",
                    port="5432"
                    )    
            
            cur = conn.cursor()

            
            cur.execute("""
                        INSERT INTO "booking-history" ( user_id, hotel_id, price, created_at)
                        VALUES (%s, %s, %s, %s)
                        RETURNING id;
                    """, ( booking['user_id'], booking['hotel_id'], booking['price'], datetime.fromisoformat( booking['created_at'] ) )
                    )
           
            new_id = cur.fetchone()[0]
        except Exception as e:
            logging.info(f"Error inserting into table booking-history: {e}")
            conn.rollback()
        
        finally:
            conn.commit()
            cur.close()
            conn.close()

        logging.info(f"Saved booking event into booking-history table with id={new_id}")


if __name__ == '__main__':
    
    crate_table_if_missing()
    
    try:
      consumer = KafkaConsumerService()
      consumer.consume_bookings(handler)
    except Exception as e:
        logging.info(f"Consumer error: {e}")
       