import grpc
from concurrent import futures
import booking_pb2
import booking_pb2_grpc
import uuid
from datetime import datetime
from typing import List, Dict
from kafka_producer import KafkaProducerService
import logging
from datetime import datetime, timezone
import psycopg2
import psycopg2.extras 

# Configure the root logger to output to the console
logging.basicConfig(
    level=logging.INFO, # Set the minimum level to log (DEBUG, INFO, WARNING, ERROR, CRITICAL)
    format='%(asctime)s - %(levelname)s - %(message)s', # Define the output format
    datefmt='%Y-%m-%d %H:%M:%S' # Define the timestamp format
)

# In-memory storage (in production, use a database)
bookings_db = {}


def crate_table_if_missing():

    conn = psycopg2.connect(
                 dbname="booking",
                 user="booking",
                 password="booking",
                 host="booking-db",
                 port="5432"
                )    
    cur = conn.cursor()
    # SQL for table creation
    create_table_query = """
    CREATE TABLE IF NOT EXISTS booking (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_id TEXT NOT NULL,
        hotel_id TEXT NOT NULL,
        promo_code TEXT,
        discount_percent DOUBLE PRECISION DEFAULT 0.0,
        price DOUBLE PRECISION NOT NULL,
        created_at TIMESTAMPTZ NOT NULL
    );
    """

    try:
        cur.execute(create_table_query)
        conn.commit()
        logging.info("Table 'bookings' created successfully.")
    except Exception as e:
        logging.info(f"Error creating table: {e}")
        conn.rollback()
    finally:
        cur.close()
        conn.close()


class BookingService(booking_pb2_grpc.BookingServiceServicer):
    
    def __init__(self):
        self.kafka_producer = KafkaProducerService()
       
    
    def CreateBooking(self, request, context):
        """Create a new booking"""
        
        logging.info(f"Create booking request {request}")
        

        booking_id = str(len(bookings_db) + 1)
        
        # Create booking record
        booking = (
            request.user_id,
            request.hotel_id,
            request.promo_code,                      
             0.0, #'discount_percent'
             9, #price
            datetime.now(timezone.utc).isoformat() # created_at
        )
        
        conn = psycopg2.connect(
                 dbname="booking",
                 user="booking",
                 password="booking",
                 host="booking-db",
                 port="5432"
                )    
        
        cur = conn.cursor()

         
        cur.execute("""
                    INSERT INTO booking ( user_id, hotel_id, promo_code, discount_percent, price, created_at)
                    VALUES (%s, %s, %s, %s, %s, %s)
                    RETURNING id;
                  """, booking)
        
        new_id = cur.fetchone()[0]


        conn.commit()
        cur.close()
        conn.close()

        logging.info(f"Saved booking request to db.")

        booking_created = {
            "event_type":"booking_created",
            "payload":{
                 'user_id': booking[0],
                 'hotel_id' : booking[1],
                 'price' : booking[4],
                 'created_at':booking[5]
            }
        }        
        self.kafka_producer.produce_message(key = None, value= booking_created)
                
        logging.info(f"Sent booking request to kafka.")                 
        # Return response
        return booking_pb2.BookingResponse(
               id = str(new_id),
               user_id = booking[0],
               hotel_id = booking[1],
               promo_code = booking[2],
               discount_percent = booking[3],
               price = booking[4],
               created_at = booking[5]
           )
    
    def ListBookings(self, request, context):
        """List bookings for a user with pagination"""
        
        logging.info(f"List bookings request {request}")
        
        conn = psycopg2.connect(
                 dbname="booking",
                 user="booking",
                 password="booking",
                 host="booking-db",
                 port="5432"
                ) 

        cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    
        query = "SELECT * FROM booking WHERE user_id = %s"
        cur.execute(query, (request.user_id,))
        bookings = cur.fetchall()
    
        cur.close()
        conn.close()

        # Convert to protobuf format
        response = []
        for booking in bookings:

            logging.info(f"{booking}")     
            response.append(booking_pb2.BookingResponse(
                id = str(booking['id']),
                user_id = booking['user_id'],
                hotel_id = booking['hotel_id'],
                promo_code = booking['promo_code'],
                discount_percent = booking['discount_percent'],
                price = booking['price'],
                created_at=str(booking['created_at'].isoformat())
            ))
            
            
                
        return booking_pb2.BookingListResponse(
            bookings=response            
        )

def serve():
    """Start the gRPC server"""
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    booking_pb2_grpc.add_BookingServiceServicer_to_server(BookingService(), server)
    server.add_insecure_port('[::]:50051')
    server.start()
    logging.info("Server started on port 50051")
    
    try:
        server.wait_for_termination()
    except KeyboardInterrupt:
        server.stop(0)
    finally:
        logging.info("Done, close.")
    

if __name__ == '__main__':
    crate_table_if_missing()
    serve()